## theoretical questions


Q.1  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans=> Vector-Vector multiplication.
Matrix-Matrix multiplication and Matrix-Vector multiplication.
Element-wise operations on vectors and matrices (i.e., adding, subtracting, multiplying, and dividing by a number )

Q.2  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans=> # mean
1. Use to calculate arithmetic mean
2. All elements have equal weight
3. Syntax :

np.mean(arr, axis = None)

where ‘arr’ is the given array.

#avrage

1. Use to calculate the arithmetic mean as well as weighted average.

2. All elements may or may not have equal weight.
Syntax :

numpy.average(arr, axis = None, weights = None)

Where ‘arr’ is the given array

 Q.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

ans=>The numpy.flip() function reverses the order of array elements along the specified axis preserving the shape of the array.

In [4]:
# example of 1D array
import numpy as np

# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])
a = np.flip(ini_array)

print("final array", str(a))


final array [5 4 6 3 2 1]


In [6]:
# example of 2D array

# initialising numpy array
ini_array = np.array([[1, 2, 3, 6, 9, 8]])
a = np.flip(ini_array)
print("final array", str(a))


final array [[8 9 6 3 2 1]]


 Q.2  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance

Ans=> We can check the datatype of Numpy array by using dtype. it returns the data type of array eliment .

Data types are help to enforce code reliability and efficiency.


Q.5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans=>  An ndarray is a usually fixed-size multidimensional container of items of the same type and size.

High-performance N-dimensional array object. 
It contains tools for integrating code from C/C++ and Fortran. 
It contains a multidimensional container for generic data. 
Additional linear algebra, Fourier transform, and random number capabilities. 
It consists of broadcasting functions.

Q.6  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans=> NumPy arrays are homogeneous and contiguous in memory, allowing for optimized processing with compiled C code. This results in faster execution times for mathematical operations and array manipulations compared to Python lists.

Q.7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

Ans=> The major difference is that np.hstack combines NumPy arrays horizontally and 
np.vstack combines arrays vertically.

Q.8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans=> The flipud() method will also reverse the Numpy array items. The numpy.flipud() method flips the array (elements in each column) up and down, keeping the shape.
 the flipr()
We may quickly reverse an array using the numpy.fliplr() method. The np.fliplr() function flips the array from left to right. The numpy.fliplr() method always takes an array as an argument and returns the same array with a left-right flip. Assuming you have a matrix, a request occurs requiring you to flip the items in each row while keeping the column intact

Q.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans=> Array splitting in NumPy is like a slice of cake. Think of each element in a NumPy array as a slice of cake. Splitting divides this “cake” into smaller “slices” (sub-arrays), often along specific dimensions or based on certain criteria. We can split horizontally, vertically, or even diagonally depending on our needs.

In [22]:
# example of array_split()
import numpy as np
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(Arr, 3)
print(array)



[array([1, 2]), array([3, 4]), array([5, 6])]


Q.10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

 Ans => Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. 

# practical questions

Q.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [49]:
import numpy as np 


array = np.random.randint(100, size=(3, 3)) 
print(array) 

[[49 79 13]
 [73 81 51]
 [79  6 56]]


In [51]:
array.T


array([[49, 73, 79],
       [79, 81,  6],
       [13, 51, 56]])

Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [54]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr1.reshape((2, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
arr1.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [62]:
# importing Numpy package 
import numpy as np 

# Creating a 2X2 Numpy matrix 
array = np.ones((4, 4)) 

print("Original array") 
print(array) 

print("\n0 on the border and 1 inside the array") 

array = np.pad(array, pad_width=1, mode='constant', 
			constant_values=0) 

print(array) 


Original array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [64]:
array.size

36

Q.4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [110]:

# Creating an array of integers from 10 to 60 using np.arange()
array = np.arange(10, 60)

print("Array of the integers from 10 to 60")

print(array) 


Array of the integers from 10 to 60
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


Q.5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element

In [72]:
arr = np.array(['python', 'Numpy','PaNdaS'])
arr
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [73]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [74]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [81]:
arr = np.array(['pw','for','skills'])
arr
np.char.join(" ", arr)

array(['p w', 'f o r', 's k i l l s'], dtype='<U11')

Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [84]:
arr1 = np.ones((3,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
arr2 = np.random.randint(10, size=(3, 4)) 
print(arr2) 

[[4 2 3 6]
 [6 2 0 6]
 [4 8 6 2]]


In [99]:
arr1 + arr2

array([[5., 3., 4., 7.],
       [7., 3., 1., 7.],
       [5., 9., 7., 3.]])

In [100]:
arr1 - arr2

array([[-3., -1., -2., -5.],
       [-5., -1.,  1., -5.],
       [-3., -7., -5., -1.]])

In [101]:
arr1 * arr2

array([[4., 2., 3., 6.],
       [6., 2., 0., 6.],
       [4., 8., 6., 2.]])

Q.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [109]:

b = np.identity(5, dtype = float)
print("Matrix b : \n", b)

a = np.identity(4)
print("\nMatrix a : \n", a)


Matrix b : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matrix a : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q.9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.



In [111]:
array = np.arange(10, 60)

print("Array of the integers from 1 to 100")
print(array) 


Array of the integers from 1 to 100
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


Q.10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [126]:

temperatures = (40, 42, 44, 40, 39, 46, 45)
temperatures
 
    

(40, 42, 44, 40, 39, 46, 45)

In [129]:
np.average(temperatures)

42.285714285714285